language: go

notificaitons:
  email:
    recipients: bluesuncorp01@gmail.com
    on_success: change
    on_failure: always

go:
  - 1.3
  - 1.4
  - tip
  
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
